### ISSUE TITLE
Create an option to filter the payment table based on the number of coins the Users own

### ISSUE THREAD

**Issue by agilitehub** [agilitehub/desoops-portal#4]
## Overview

In some instances, instead of paying all coin holders, you want the option only to pay coin holders who own more or less than a specified amount of coins.

## Tasks

- [x] After all 3 Steps have been provided, create a Switch control with a Yes/No option (Defaulted to No)
- [x] The label of the Switch control will be "Filter Users based on Coins Owned"
- [x] If switched to Yes, display a label "Where Coin amount is", with a Select control and a Number field
- [x] The select control must include the following values

- -Select- (Default Label, but the value is blank)
- Greater than
- Greater than equal to
- Less than
- Less than equal to

- [x] The Number field must include a numeric value not less than 0
- [x] Whenever these values are changed, re-calculate the table accordingly
