### ISSUE TITLE
Create an option to filter the payment table based on the Users position in the Table

### ISSUE THREAD

**Issue by agilitehub** [agilitehub/desoops-portal#5]
## Overview

In some instances, instead of paying all coin holders, you want the option to only pay the top x coin holders based on their position in the Payment Table.

## Tasks

- [ ] After all 3 Steps have been provided, create a Switch control with a Yes/No option (Defaulted to No)
- [ ] The label of the Switch control will be "Return only the Top/Bottom Users"
- [ ] If switched to Yes, first display a label "Return", then a Select control, a Number field, and finally a label "Users"
- [ ] The select control must include the following values

- -Select- (Default Label, but the value is blank)
- Top
- Bottom

- [ ] The Number field must include a numeric value not less than 0 and not greater than the total users in the Payment Table
- [ ] Whenever these values are changed, re-calculate the table accordingly
