### ISSUE TITLE
Create option to filter payment table based on the Active Users

### ISSUE THREAD

**Issue by agilitehub** [agilitehub/desoops-portal#6]
## Overview

In certain cases, instead of paying all coin holders, you want the option to only pay who have been active recently.

## Tasks

- [ ] After all 3 Steps have been provided, create a Switch control with a Yes/No option (Defaulted to No)
- [ ] The label of the Switch control will be "Return only Active Users"
- [ ] If switched to Yes, first display a label "Since", then a Number field, and finally a label "days ago"

- [ ] The Number field must include a numeric value not less than 0

e.g. Since 10 days ago

- [ ] Whenever these values are changed, re-calculate the table accordingly
