### ISSUE TITLE
Allow payment to be spread across selected users based on their % holding or spread equally

### ISSUE THREAD

**Issue by agilitehub** [agilitehub/desoops-portal#7]
## Overview

At the moment, DeSo Ops spreads the amount to be paid across all selected users in the Payment Table based on the % of coins they own. There are scenarios where the amount to be paid must be spread equally to all selected users, regardless of the number of coins they own.

## Tasks

- [x] Underneath the Amount to be paid field, add a Radio control with the following criteria:

- Label = "Spread amount based on:"
- Radio Option = "% Coin Ownership" (Default)
- Radio Option = "Equal Spread"

- [x] Update calculation logic to be based on these 2 rules
- [x] Whenever this value changes, re-calculate the table accordingly
